services:
  frontend:
    image: "node"
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    tty: true        
    stdin_open: true 
    environment:
      - FORCE_COLOR=1
    volumes:
      - ./frontend:/home/node/app
    command: sh -c "npm install && npm run build && npm run start"
    depends_on:
      - backend
    networks:
      - fullstack
      
  backend:
    build: ./ 
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/src/foyer-shifts
      - /tmp/dderny/ttarget:/usr/src/foyer-shifts/target
    environment:
      - DATABASE_URL=mariadb://root:debug@database:3306/foyer
    depends_on:
      database:
        condition: service_healthy
    networks:
      - fullstack

  database:
    image: mariadb:latest 
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=debug
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullstack
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  fullstack:
    driver: bridge
